version: "3"
services:
  chowdown:
    container_name: chowdown
    image: chemxboy/chowdown:latest
    volumes:
      - /opt/appdata/chowdown:/config # Align permissions to desired user set in environment
    restart: unless-stopped
    environment:
     - PUID=1000 # set to PUID of config directory owner
     - PGID=1000 # set to PGID of config directory owner
    ports:
      - 4000:4000/tcp