version: "3"
services:
  chowdown:
    container_name: chowdown
    image: tylerobara/chowdown:latest
    volumes:
      - /opt/appdata/chowdown:/config # Align permissions to desired user set in environment
    restart: unless-stopped
    environment:
     - PUID=65534 # set to PUID of config directory owner
     - PGID=65534 # set to PGID of config directory owner
    ports:
      - "4000:4000"